# Generated by Django 5.2.7 on 2025-11-22 23:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sdc_client', '0002_warehouse_inventoryitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeasurementUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Nombre (ej. Kilogramo)')),
                ('symbol', models.CharField(max_length=10, verbose_name='Símbolo (ej. kg)')),
                ('max_limit_normal', models.DecimalField(decimal_places=2, default=10.0, max_digits=10, verbose_name='Límite para usuario normal')),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='sdc_client.measurementunit', verbose_name='Unidad'),
        ),
    ]
