# Generated by Django 5.2.7 on 2025-11-29 22:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sdc_client', '0003_measurementunit_post_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='institution',
            name='warehouses',
            field=models.ManyToManyField(blank=True, related_name='institutions', to='sdc_client.warehouse', verbose_name='Almacenes Asignados'),
        ),
        migrations.AddField(
            model_name='post',
            name='warehouse',
            field=models.ForeignKey(blank=True, help_text='Almacén relacionado a esta operación (Solo Instituciones)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='sdc_client.warehouse', verbose_name='Almacén (Origen/Destino)'),
        ),
    ]
