# Generated by Django 5.2.7 on 2025-12-01 01:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sdc_client', '0004_institution_warehouses_post_warehouse'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField(verbose_name='Motivo del reporte')),
                ('status', models.CharField(choices=[('PENDING', 'Pendiente de Revisión'), ('VALIDATED', 'Reporte Validado (Publicación Eliminada)'), ('REJECTED', 'Reporte Rechazado (Falso Positivo)')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='sdc_client.post', verbose_name='Publicación Reportada')),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario que reporta')),
            ],
        ),
    ]
