# Generated by Django 5.2.7 on 2025-12-01 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sdc_client', '0005_report'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='phone',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='donee',
            name='city',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='donee',
            name='second_surname',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='donee',
            name='state',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='donor',
            name='city',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='donor',
            name='second_surname',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='donor',
            name='state',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='institution',
            name='address',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='institution',
            name='city',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='institution',
            name='state',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
